### ISSUE TITLE
Programs do not show in UI.

### ISSUE THREAD

**Issue by Ziflin** [genielabs/HomeGenie-Android#5]
I have created a simple program to turn off lights when going to bed and added it to one of my Groups.  It displays and appears to work properly from the Web UI, but the program is not listed on the Android UI.  Is this a bug or is this feature not yet implemented?

**Comment by genielabs** [comment]
Could not replicate this issue. Please be more specific. Can you give a screenshot or more detailed example about how to reproduce the issue?

**Comment by rkoshak** [comment]
OK, here are some screenshots with more explanation.

I am currently running HomeGenie Server version r431 and HomeGenie Android
App version 1.0.16.

This is what my Control Dashboard looks like in a browser on a computer. In
this case the browser is Chrome and the computer is Windows 8.1.
[image: Inline image 1]

The item to pay attention to is the yellow "Garage" button in the upper
center. That button represents an automation program that calls a web page
to open or close my garage. The code is as follows:

Trigger Code:
[image: Inline image 2]

Program Code:
[image: Inline image 3]

Unfortunately the Volume Down button on my phone is broken and my phone
isn't rooted so I've yet to find a way to take a screenshot from my phone.
Hopefully my description will be adequate. If not I'll try to borrow
someone else's phone to take a picture of mine.

When I bring the HomeGenie web page up on my Android phone (Motorola Moto X
2013 edition running Android version 4.4.4) using Chrome I see the "Garage
Button" as expected and it works just like it does in the browser on my
computer.

When I bring up the HomeGenie App it only shows the weather and the two
lamps in the Dashboard but no "Garage Button." I've tried other automation
programs as well and get the same result. The icons appear when i use the
browser but do not when I use the app.

Thanks

Rich

Rich Koshak

**Comment by genielabs** [comment]
@rkoshak @Ziflin to run programs/scenarios use the "Play" button in the top menu.
For more information also read this forum post:
http://www.homegenie.it/forum/index.php?topic=506.msg2895#msg2895
