### ISSUE TITLE
No modules/widgets displayed with r453

### ISSUE THREAD

**Issue by bkenobi** [genielabs/HomeGenie-Android#6]
After updating to r453, I am no longer seeing any content on the Android app.  I can see the correct tabs, but no modules/widgets are populated.  I do not know when this issue occurred, but I know it worked a few weeks ago and it does not at r453.

**Comment by genielabs** [comment]
HomeGenie Droid 1.0.16 has just been published and will be available soon on Google Play.
Let me know if the issue is fixed once updated.
